Scalar render parfix
Alpine-DAV/vtk-h pull request #191
Opened 2020-12-18 02:31 UTC by nicolemarsaglia

Fix what I broke.

2020-12-21 20:59 UTC, nicolemarsaglia commented
This is to undo breaking scalar renderer in parallel.

2020-12-22 20:03 UTC, mclarsen requested changes
Without the prints we are good.

2020-12-22 20:03 UTC, mclarsen commented on src/vtkh/compositing/PayloadCompositor.cpp
> +  std::cerr << "image size: " << m_images.size() << std::endl;
Do you need the print statements?

2020-12-22 20:28 UTC, nicolemarsaglia commented on src/vtkh/compositing/PayloadCompositor.cpp
> +  std::cerr << "image size: " << m_images.size() << std::endl;
Nope. my bad.

2020-12-22 20:35 UTC, nicolemarsaglia commented on src/vtkh/compositing/PayloadCompositor.cpp
> +  std::cerr << "image size: " << m_images.size() << std::endl;
I didn't mean to push this file.

2020-12-22 21:00 UTC, mclarsen approved these changes

2020-12-22 21:04 UTC, mclarsen commented
The CI wont pass because we have detected blt time travel. You need to `git submodule update` to get the current version. Also you could
```
cd src/blt
git checkout 86a7d6b5ee93d8b7b3233a3e54a4f06f8d8308d3
cd ../..
git push
```

2020-12-22 21:16 UTC, merged